sudo: required

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_script:
- mkdir $HOME/.kube || true
- touch $HOME/.kube/config
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.33.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- minikube version
- sudo minikube config set WantReportErrorPrompt false
- sudo minikube start --vm-driver=none --kubernetes-version=v1.9.0
- minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
- kubectl cluster-info
- kubectl get pods --all-namespaces
- kubectl create namespace travis-test
